dependencies:
  - setuptools_scm
  - numpy
  - scipy
  - matplotlib
  - astropy
  - aplpy
  - dask[complete]
  - pip
  - pip:
      - --index-url https://casa-pip.nrao.edu/repository/pypi-casa-release/simple casatools
      - --index-url https://casa-pip.nrao.edu/repository/pypi-casa-release/simple casatasks